overrides:
  effect: 4.0.0-rc.109
  vite: "catalog:"
  vitest: "catalog:"

allowBuilds:
  "@parcel/watcher": true
  "@playwright/browser-chromium": false
  "@swc/core": false
  esbuild: true
  msgpackr-extract: true
  onnxruntime-node: false
  protobufjs: false
  sharp: false

minimumReleaseAgeExclude:
  - "@effect/platform-node-shared@4.0.0-rc.109"
  - "@effect/platform-node@4.0.0-rc.109"
  - "@effect/vitest@4.0.0-rc.109"
  - effect@4.0.0-rc.109
  - knip@6.31.0
  - "@uinaf/skillcheck@0.4.0"
  - "@putdotio/sdk@11.3.0"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10
  "@vitest/coverage-v8": 4.1.10
  vite-plus: 0.2.9
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
