export const ENV_CLI_CLIENT_NAME = "PUTIO_CLI_CLIENT_NAME";
export const ENV_CLI_WEB_APP_URL = "PUTIO_CLI_WEB_APP_URL";
export const ENV_CLI_CONFIG_PATH = "PUTIO_CLI_CONFIG_PATH";
export const ENV_API_BASE_URL = "PUTIO_CLI_API_BASE_URL";
export const ENV_CLI_TOKEN = "PUTIO_CLI_TOKEN";
export const ENV_XDG_CONFIG_HOME = "XDG_CONFIG_HOME";
